### ISSUE TITLE
Question: How to use typetag with associated types

### ISSUE THREAD

**Issue by ISibboI** [dtolnay/typetag#2]
I have a trait like so:
```rust
#[typetag::serde(tag = "type")]
pub trait Variable {
    type NativeType;
    fn native_value(&self) -> &Self::NativeType;
}
```

It does not compile as it asks me to specify the associtated type `NativeType`.
What does this mean?

**Comment by ISibboI** [comment]
Digging further, this seems to be caused by not being able to specify `dyn Variable` without specifying `NativeType`.

**Comment by dtolnay** [comment]
Typetag makes it possible to serialize and deserialize `dyn Trait` for object-safe traits, but as you noticed, for your trait `dyn Variable` cannot exist because different impls of the trait would have different signatures for Variable::native_value.

**Comment by jbirnick** [comment]
Having basically the same problem. My use case is described here: https://users.rust-lang.org/t/serde-and-trait-objects-and-associated-types/122999/1

Having a different signature for different types is certainly an issue but in my case I think it can be solved by making the return type of `dyn` type.

Still trying to figure out how I could achieve something like TypeTag in that context..
