### ISSUE TITLE
Deserializing Traits with Generic Methods for Visitor Pattern

### ISSUE THREAD

**Issue by toadzky** [dtolnay/typetag#20]
I know that there are other issues related to this, but they all seem to be about something different and I'm not sure if this is actually the same thing. 

I'm trying to implement the visitor pattern. I have 2 traits:
```rust
pub trait EventVisitor {
    type Result;

    fn visit(&mut self, event: &EventA) -> Self::Result;
    fn visit(&mut self, event: &EventB) -> Self::Result;
}

pub trait Event {
    fn accept<V: EventVisitor>(&self, visitor: &mut V) -> V::Result;
}
```

because of the generic accept method in the trait, which has nothing to do with the contents of the implementation struct, the type tag doesn't work.

i'd rather not use an enum for this because the struct have a bunch of fields and implementing traits on enums is a PITA.

**Comment by Gowee** [comment]
I am also stuck on the limitation. Are there any workarounds? 🤔

**Comment by dtolnay** [comment]
If you want to do things with `dyn Event`, you need to add a `where Self: Sized` where-clause on the `accept` function so that it doesn't appear in the trait object. Trait objects are not allowed to contain generic function. This is limitation of Rust not the typetag crate.
