### ISSUE TITLE
Does this work with Rc<dyn Trait>?

### ISSUE THREAD

**Issue by xfbs** [dtolnay/typetag#23]
Hey, this is really cool! Shouldn't this technically also (be possible to made to) work with `Rc<dyn Trait>`? (I'm aware of the caveats of serialising Rc<>).

**Comment by dtolnay** [comment]
Yes it works out of the box with Rc\<dyn Trait\>.

**Comment by xfbs** [comment]
Awesome! Thanks for getting back to be so quick, I'll close this issue then.
