### ISSUE TITLE
Integration with Clone

### ISSUE THREAD

**Issue by SirWindfield** [dtolnay/typetag#24]
Hey!

I am a little bit confused about the error message I get with the following trait:
```rust
#[typedef::serde(tag = "layout")]
pub trait Layout: Clone + Debug {
   // ...
}

#[typedef::serde]
impl Layout for SidedLayout {
    // ...
}
```

I get the following error about 10 times printed to the console:
```
#[typetag::serde(tag = "layout")]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `layout::Layout` cannot be made into an object
14 | pub trait Layout: Clone + Debug {
   |           ------  ----- ...because it requires `Self: Sized`
   |           |
   |           this trait cannot be made into an object...
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by dtolnay** [comment]
There isn't a trait object for the Clone trait. You would need to use DynClone. https://github.com/dtolnay/dyn-clone

**Comment by SirWindfield** [comment]
Oh wow, I actually didn't new that `Clone` is not a trait. Is there a specific reason for it not being one? 🤔 
And I am not surprised that you have a crate that fits perfectly here haha ;)
