### ISSUE TITLE
Arc<Box<dyn MyTrait>> doesn't serialize/deserialize

### ISSUE THREAD

**Issue by aaronshim** [dtolnay/typetag#26]
I have a blank project with the following code snippet:
```
use std::sync::Arc;
use serde_derive::{Deserialize, Serialize};

#[typetag::serde]
trait MyTrait: Send + Sync {}

#[derive(Serialize, Deserialize)]
struct MyType {}

#[typetag::serde]
impl MyTrait for MyType {}

#[derive(Serialize, Deserialize)]
struct Foo {
    x: Arc<Box<dyn MyTrait>>,
}
```

I get the following errors when I try to compile:
```
error[E0277]: the trait bound `std::sync::Arc<std::boxed::Box<dyn MyTrait>>: _::_serde::Serialize` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Arc<Box<dyn MyTrait>>,
   |     ^ the trait `_::_serde::Serialize` is not implemented for `std::sync::Arc<std::boxed::Box<dyn MyTrait>>`
   |
   = note: required by `_::_serde::ser::SerializeStruct::serialize_field`

error[E0277]: the trait bound `std::sync::Arc<std::boxed::Box<dyn MyTrait>>: _::_serde::Deserialize<'_>` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Arc<Box<dyn MyTrait>>,
   |     ^ the trait `_::_serde::Deserialize<'_>` is not implemented for `std::sync::Arc<std::boxed::Box<dyn MyTrait>>`
   |
   = note: required by `_::_serde::de::SeqAccess::next_element`

error[E0277]: the trait bound `std::sync::Arc<std::boxed::Box<dyn MyTrait>>: _::_serde::Deserialize<'_>` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Arc<Box<dyn MyTrait>>,
   |     ^ the trait `_::_serde::Deserialize<'_>` is not implemented for `std::sync::Arc<std::boxed::Box<dyn MyTrait>>`
   |
   = note: required by `_::_serde::de::MapAccess::next_value`
```

1. Is `Arc` currently supported? The documentation seems to suggest that `Box` is, and #23 seems to suggest that `Rc` is, but is `Arc`? I know I can write a manual implementation of Serialize/Deserialize to make this work, but this is a lot of (not very aesthetic) code.
2. If `Arc` (and consequently `Rc`) are features that are meant to work, would it be helpful if I went and wrote these test cases? I didn't see any in the test file.
3. Would it be possible (either now or in the future) to serialize/deserialize structs with fields that are `Arc<dyn MyTrait>` rather than having to use `Box<dyn MyTrait>`? `Arc<T>` implements `From<Box<T>>`, so I think this should be possible while manually implementing Deserialize, but I was wondering whether this is something that this library could support.

Thanks so much all your work on this awesome library!

**Comment by dtolnay** [comment]
I don't think your issue is specific to typetag. You need `features = ["rc"]` enabled on the serde dependency in order for Rc\<T\>/Arc\<T\> to be deserializable.

`Arc<dyn MyTrait>` already works as long as you are using rustc >=1.21.0.

I'll go ahead and close this since there isn't anything in this library that would be relevant to Rc/Arc support.

**Comment by aaronshim** [comment]
Thanks!
