### ISSUE TITLE
Is it possible to make ctor dependency optional?

### ISSUE THREAD

**Issue by vi** [dtolnay/typetag#30]
Is it possible to make a cfg-selected mode where you need to explicitly register all possible types manually in `fn main` instead of relying on `intentory`/`ctor`? Less automatic, more portable.

Or should such explicit mode  be added to `inventory` first?

**Comment by dtolnay** [comment]
I would prefer not to add this, but it would be reasonable for someone to maintain a different implementation which can be used this way.

**Comment by vi** [comment]
Why is the issue closed as "completed" instead of "not planned"?
