### ISSUE TITLE
Please add README and LICENSE files in typetag-impl as well

### ISSUE THREAD

**Issue by olivierlemasle** [dtolnay/typetag#32]
Fedora packager here; I'm packaging crates `typetag` and `typetag-impl` as Fedora packages.

Would you mind adding README and LICENSE files in typetag-impl crate?

**Comment by dtolnay** [comment]
Fixed in 0.1.7. https://docs.rs/crate/typetag-impl/0.1.7/source/

**Comment by olivierlemasle** [comment]
Thank you @dtolnay!
