### ISSUE TITLE
Not finding a variant in some cases

### ISSUE THREAD

**Issue by chinedufn** [dtolnay/typetag#34]
I have a peculiar case in a large codebase that I am struggling to reproduce in a small example repo. 

In the meantime, I am opening this issue in case it sparks any thoughts.

---

I have a trait called `Asset` and three types that implement it.

```rust
#[typetag::serde]
impl Asset for ArmatureAsset {
    // ...
}

#[typetag::serde]
impl Asset for MeshAsset {
    // ...
}

#[typetag::serde]
impl Asset for Box<dyn Asset> {
    // ...
}
```

When I try to deserialize `let _: Box<dyn Asset> = bincode::deserialize(&armature_asset_bytes).unwrap();` I get the following error.

```
called `Result::unwrap()` on an `Err` value: Custom("unknown variant `ArmatureAsset`, expected `Box` or `MeshAsset`")
```

Now.. If I add a fourth `impl Asset` such as

```rust
#[typetag::serde]
impl Asset for Foo {
    // ...
}
```

I can deserialize some `ArmatureAsset` bytes  as a `Box<dyn Asset>` just fine. No errors.

So.. It seems as if `typetag` or one of the downstream crates can sometimes miss out on a type when building the map of all types that implement a trait.

I tried to create a simple repo to reproduce this using three empty structs and a fake trait with no methods, but I did not get the error in the repo. Suggesting that something non-obvious about my workspace or types is causing this issue.

For now I will just use my `impl Asset for Foo` hack described above.

**Comment by chinedufn** [comment]
Interesting.. I moved by `impl Asset for Foo` hack to another module and now I get.

```
called `Result::unwrap()` on an `Err` value: Custom("unknown variant `ArmatureAsset`, expected one of `Box`, `Foo`, `MeshAsset`")
```

So it seems like where these traits impls are defined matters.

**Comment by dtolnay** [comment]
It's probably this rust bug. :( https://github.com/rust-lang/rust/issues/47384

**Comment by chinedufn** [comment]
Ah I see, thanks for the link. 

Ok cool. Luckily I'm good for now with the aforementioned hack.

I'll close since it doesn't seem like there is anything work to do on the typetag side, but feel free to re-open if you want this tracked.

As always, thank you for your speedy help.
