### ISSUE TITLE
Is Serialize mandatory?

### ISSUE THREAD

**Issue by DBLouis** [dtolnay/typetag#5]
It seems that the Serialize trait is mandatory to use typetag. Is there a reason?
Why should not it be possible to just deserialize?

**Comment by dtolnay** [comment]
To generate deserialization only, replace every #[typetag::serde] with #[typetag::deserialize]. I wasn't sure whether anyone would need this so I have not documented it yet, but it should work! I'll label this as a documentation issue.

**Comment by rukai** [comment]
I needed this!
It seems this issue was accidentally closed before the functionality was documented.
