### ISSUE TITLE
Using typetag with interior mutability

### ISSUE THREAD

**Issue by BattleDash** [dtolnay/typetag#65]
Using serde's `rc` feature allows typetag to work with `Rc`/`Arc`, and normally serde allows [usage of types that provide interior mutability](https://github.com/serde-rs/serde/pull/882), like `RefCell`.

However, using typetag with the following code:
```rust
#[typetag::serde]
trait Foo {}

#[derive(Serialize, Deserialize)]
struct Bar {
    foo: Rc<RefCell<dyn Foo>>
}
```

Results in:
```rust
required for `RefCell<dyn Foo>` to implement `_::_serde::Deserialize<'_>`
```

Am I doing something wrong, or is this a limitation?

Thanks!

**Comment by dtolnay** [comment]
You would need to use `Rc<RefCell<Box<dyn Foo>>>`.
