### ISSUE TITLE
Add support for setting the name to a number

### ISSUE THREAD

**Issue by Tutul-** [dtolnay/typetag#70]
Working on a project with a front written in a different language, the JSON was fix to:
```json
{
    "id": 512,
    "data": {
    }
}
```
When the ID was a way to know how the payload (in data) was to be read.

I managed to get close to that result with the following code:
```rust
#[typetag::serde(tag = "id", content = "data")]
pub trait MessagePayload {
    fn as_any(&self) -> &dyn Any;
    fn get_type(&self) -> MessageType;
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct Package {
    #[serde(flatten)]
    pub content: Box<dyn MessagePayload>
}

impl Package {
    fn new(content: Box<dyn MessagePayload>) -> Self {
        Package { content }
    }
    pub fn get_type(&self) -> MessageType {
        self.content.get_type()
    }
}

#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct LobbyInformation {
    pub server_name: String,
    pub number_of_slots: u32,
    pub played_games: u32,
    pub clients: Vec<LobbyInformationClientsList>,
}

#[typetag::serde(name = "0")]
impl MessagePayload for LobbyInformation {
    fn as_any(&self) -> &dyn Any {
        self
    }
    fn get_type(&self) -> MessageType {
        MessageType::LobbyInformation
    }
}
```

Here I setup the tag to be "id" and its value to be the code (there is an enum somewhere in the doc with all the codes for each package). But the value is set as a string, not a number...
I also use "flatten" to avoid the redundant object.

The code can read back the object using "get_type()" to figure out the real Object behind the "dyn trait" Box, then use the "as_any().downcast_ref::<STRUCT>()" to access the payload content.

I would like  for `#[typetag::serde(name = "0")]` to support either a number or provide something like "name_number" that convert the string in the macro to a number in the json.

I apologize if I missed something already present in the lib that could do that

**Comment by dtolnay** [comment]
I would prefer not to build this into this crate. But I would be interested in someone else making a more fully featured library for trait object serialization, which could support this case (and maybe a few of the other feature requests from this repo).
