### ISSUE TITLE
re-exporting `typetag` from another crate almost works but fails when `__INVENTORY` references `typetag` without re-export path

### ISSUE THREAD

**Issue by j-n-f** [dtolnay/typetag#88]
I have a library that has a derive macro, and I'm trying to have it emit a trait impl with `#[mylib::exports::typetag::serde]` on them.

I couldn't get it to work without having the crate (call it `myapp`) using `mylib` add `typetag` as a dependency. After digging into this with `cargo expand`, I see that the `static __INVENTORY` bit is referencing `typetag` without the prefix I'd like it to have.

Would something like `#[typetag::serde(typetag_prefix = "mylib::")]` be feasible? (as an instruction to the code generating `static __INVENTORY`)

I can't imagine I'm the only person who would want to do this with a derive macro.

I might try hacking this in for my own amusement, but is this likely to get accepted if I make a PR?

**Comment by dtolnay** [comment]
I would prefer not to support such a workaround in this crate. But in case you are interested in working on this instead, https://github.com/rust-lang/rust/issues/54363#issuecomment-1237544924 describes what I think is a good design for proc macro re-exporting.
